version: "3.7"
services:
  radio-app:
    build:
      args:
        user: unp
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: radio-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - radio-laravel
  radio-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: radio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - radio-laravel
    ports:
      - "3310:3306"
  radio-nginx:
    image: nginx:1.17-alpine
    container_name: radio-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - radio-laravel
networks:
  radio-laravel:
    driver: bridge